#!/bin/bash


        Xint=1.0
        Yint=1000.0
        Clip_percent=90

#./savesismo ./OUTPUT_FILES/Up_file_single.su -save=./OUTPUT_FILES/seismo.png -c=$Clip_percent -xint=$Xint -yint=$Yint > /dev/null &

#cp DATA/Uexp.txt OUTPUT_FILES/Uexp.txt

. zall_plot_su

python zconvert_su_to_mat
python zsavesismo

. zcopy_files










