#!/bin/bash 

##### gnuplot common commands 


(obspy) [jiazeh@paris programs_fortran]$ gnuplot

	G N U P L O T
	Version 4.6 patchlevel 2    last modified 2013-03-14 
	Build System: Linux x86_64

	Copyright (C) 1986-1993, 1998, 2004, 2007-2013
	Thomas Williams, Colin Kelley and many others

	gnuplot home:     http://www.gnuplot.info
	faq, bugs, etc:   type "help FAQ"
	immediate help:   type "help"  (plot window: hit 'h')

Terminal type set to 'x11'
gnuplot> plot 'data.dat' using 1:2
gnuplot> 

# get out of gnuplot 
gnuplot> quit

### run gnuplot in bash with seperate style file 
## create a style file 
set terminal pngcairo  transparent enhanced font "arial,10" fontscale 1.0 size 500, 300
set output 'plot.png'
set title 'sin(x) / (x+1)'
set xlabel 'Time'
set ylabel 'Energy'
set grid
set key off
plot 'data.dat' with linespoints ls 6 lc 7

## run this in command line 
(obspy) [jiazeh@paris programs_fortran]$ gnuplot style.gnu





