#!/bin/bash 

### generate images from bin files automatically, in parallel 
## Creation time: Tue Jun 11 15:59:47 UTC 2018
## Revision time: 
## Sun Nov  4 10:13:31 EST 2018
## updates: use ./zpara_headers


## Jiaze He, jiazeh@princeton.edu



traces_DIR=traces

if [ -d "$traces_DIR" ]; then
    echo 'nothing'
  else
    echo 'make a folder'
    mkdir "./output/$traces_DIR"
fi


############## parameter grebbing ################
./zpara_headers

############## Plot the seismograms ################

	for n_event in `seq 0 $Nevent` ; do
		NE="$(printf "%06d" $n_event)"
		echo 'the number of events for seimography generation is '$NE
                su_dir=./scratch/solver/$NE/traces
                prop=disp
                if [ "$AC_or_El" == "$str" ]
                then
                pngfile="./output/traces/obs_${prop}_x_event_${NE}.png"
                seistitle="obs_${prop}_x_event_${NE}"
                ./savesismo "$su_dir/obs/Ux_file_single.su" -save=$pngfile -t=$seistitle -xint=$Xint -yint=$Yint > /dev/null & 
                pngfile="./output/traces/obs_${prop}_z_event_${NE}.png"
                seistitle="obs_${prop}_z_event_${NE}"
                #./savesismo "$su_dir/obs/Uz_file_single.su" -save=$pngfile -t=$seistitle -xint=$Xint -yint=$Yint > /dev/null & 

                pngfile="./output/traces/syn_${prop}_x_event_${NE}.png"
                seistitle="syn_${prop}_x_event_${NE}"
                ./savesismo "$su_dir/syn/Ux_file_single.su" -save=$pngfile -t=$seistitle -xint=$Xint -yint=$Yint > /dev/null &
                pngfile="./output/traces/syn_${prop}_z_event_${NE}.png"
                seistitle="syn_${prop}_z_event_${NE}"
                #./savesismo "$su_dir/syn/Uz_file_single.su" -save=$pngfile -t=$seistitle -xint=$Xint -yint=$Yint > /dev/null &

                pngfile="./output/traces/last_adj_${prop}_x_event_${NE}.png"
                seistitle="last_adj_${prop}_x_event_${NE}"
                ./savesismo "$su_dir/adj/Ux_file_single.su.adj" -save=$pngfile -t=$seistitle -xint=$Xint -yint=$Yint > /dev/null &
                pngfile="./output/traces/last_adj_${prop}_z_event_${NE}.png"
                seistitle="last_adj_${prop}_z_event_${NE}"
                #./savesismo "$su_dir/adj/Uz_file_single.su.adj" -save=$pngfile -t=$seistitle -xint=$Xint -yint=$Yint > /dev/null &

                else
                ./savesismo ./scratch/solver/$NE/traces/obs/Up_file_single.su -save=./output/traces/obs_event_$NE.png -c=$Clip_percent -xint=$Xint -yint=$Yint > /dev/null & 
                ./savesismo ./scratch/solver/$NE/traces/syn/Up_file_single.su -save=./output/traces/syn_event_$NE.png -c=$Clip_percent -xint=$Xint -yint=$Yint > /dev/null &
                ./savesismo ./scratch/solver/$NE/traces/adj/Up_file_single.su.adj -save=./output/traces/last_adj_event_$NE.png -c=$Clip_percent -xint=$Xint -yint=$Yint > /dev/null &               
                fi
	done
	wait

########################## Plot the seismograms ################



############## Plot the models ################
## see if png files exist
	#count=`ls -1 ./output/*.png 2>/dev/null | wc -l`
        if [ $count -eq 0 ]
        then
        echo 'nothing'
        else
        echo $count
        rm ./output/*.png
        fi

# i.e., 3 jobs each loop, then total jobs perchuck is 3*jobs_perchuck = 30; this number
############# Plot the models ################
# should be larger than the number of cores (to make the most use of the computer)
# should also be small enough to make the computers memory not blow up

#        if [ "$AC_or_El" == "$str" ]
#        then
#        echo 'vp lssajflsjdsjkdfk'
        ./zplotallmodel 'vp' > zplotall_log.txt
        ./zplotallmodel 'vs' > zplotall_log2.txt
#        else
#        ./zplotallmodel 'vs'
#        fi
# input what to plot 
##	filename2='vs' # 'vp','vs','*'(for *, see what has been excluded for plotting in zplotbin)
#	for i in `seq 0 $Nloop`;do
#		for j in `seq 1 $jobs_perchuck` ;do
#		k=$((10*$i+$j))
#		if [ "$k" -gt "$Nit" ]
#		then
#		break  # Skip entire rest of loop.
#		fi
#		K="$(printf "%04d" $k)"
#		dirname=$(printf "./output/model_$K")
#		fullp=$(printf "./output/model_$K_$filename2.bin");
#		echo $fullp
#		./zplotbin $dirname $filename2 $k &
##       	    cp $REP/model_true/*_[xz].bin $REP/output/model_$K
##       	    python $REP/plotbin $REP/output/model_$K $REP/Images/$variable/model/It$K $variable  >> xxx &
##       	    ./plot_grad_and_diff $k $variable $REP/Images/$variable/analyse/It$K >> xxx &
#		done
#	wait
#	done
wait	
########################## Plot the models ################

echo 'number of time steps is '$NSTEP 
echo 'bk path is '$foldname_for_results_saving
./plotvp ./model_true/ $filename2 

echo "plotting png has been completed"
#cp -fr "$foldname_for_results_saving" "$foldname_for_results_saving"/
#rsync -av --progress ./* "$foldname_for_results_saving"/ --exclude "$foldname_for_results_saving"/


# cp -r output/ "$foldname_for_results_saving"/ &
# cp -r output.stats/ "$foldname_for_results_saving"/ &
# cp -r specfem_data/ "$foldname_for_results_saving"/ &
# cp -r z* "$foldname_for_results_saving"/ &
# cp -r p* "$foldname_for_results_saving"/ &
# cp -r v* "$foldname_for_results_saving"/ &
# cp -r sa* "$foldname_for_results_saving"/ &
# cp -r p* "$foldname_for_results_saving"/ &

#echo "copying files has been completed"
#cp -r output/* yyoutput/newoutput/
#for i in `seq 0 $Nit`;
#do
#    #dirname=./output/model_0001
#    dirname=$(printf "./output/model_%04d" $i)
#    filenames2=_vp
#    fullp=$dirname/proc000000$filenames2.bin
#    echo $fullp
#    #vi $fullp	
#    ./zplotbin $dirname 'vp' $i
#    #./zplotbin $dirname '*' $i 
#done
