#!/bin/sh

echo "switch to the path and folder to my download"

final_dir="$HOME/Dropbox\ \(Princeton\)/Sync/princeton/Medical_FWI_research_mine/My_work_great_examples"

eval cd $final_dir
xdg-open vp_inversion_sp2d.odp

#cd /home/jiazeh/Desktop/my_files/my_bin
