#!/bin/sh

echo "switch to the path and folder to python2  playground under venv environment"

#init_dir=$HOME/Desktop/my_files/py2project 

cd $init_dir

#source venv/bin/activate

final_dir=$HOME/Desktop/my_files/py2project/pythonvenv_playground

cd $final_dir

#jp

#cd /home/jiazeh/Desktop/my_files/my_bin
