#!/bin/bash

ntask=$1
exe=$2
path=$3
class=$4
func=$5
env=$6

k=0;
#for host in $hosts;
for k in $(seq 0 $(($ntask-1)));
do
    #ssh $(hostname) "export SEISFLOWS_TASK_ID=$k; $exe $path $class $func $env" &
    srun --gres=gpu:1 -N 1 -n 1 $exe $path $class $func "SEISFLOWS_TASK_ID=$k,"$env &
    #k=$((k+1));
    #sleep 0.1
done
wait

