#!/bin/sh
echo "preparation for penn state - efficient"
#cygstart /cygdrive/d/dk_ze/IamAProgrammer/Machine_Learning/DataSciencePython/DataScience/DataScience-Python3
cygstart /cygdrive/d/dk_ze/Current\ Research/1D\ Jiaze\ research\ experience/Interview/How\ to\ prepare\ on\ Campus\ interview
#cygstart chrome "http://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPRegressor.html"
cygstart /cygdrive/c/Program\ Files/Tracker\ Software/PDF\ Viewer/PDFXCview.exe
cygstart /cygdrive/c/JH_fast/PennState/Full_Efforts_Prepare/Research_Seminar
#cygstart /cygdrive/d/dk_ze/IamAProgrammer/How\ to\ find\ a\ job\ 2017/Jobs/PennState/Full_Efforts_Prepare
cygstart /cygdrive/c/JH_fast/PennState/Full_Efforts_Prepare/Teaming_Seminar/Myslides
cygstart /cygdrive/c/JH_fast
cygstart /cygdrive/c/JH_fast/PennState/Full_Efforts_Prepare/Teaming_Seminar/silibi

#cygstart /cygdrive/d/dk_ze/IamAProgrammer/How\ to\ find\ a\ job\ 2017/job\ hunting\ preparation/xmind-portable-3.3.1.201212250029/XMind_Windows
#cygstart /cygdrive/d/dk_ze/IamAProgrammer/How\ to\ find\ a\ job\ 2017/job\ hunting\ preparation/xmind-portable-3.3.1.201212250029/XMind_Windows/XMind.exe

cygstart /cygdrive/c/Program\ Files\ \(x86\)/Mosaico/Mosaico.exe