#!/bin/sh
echo "open the video list of fang shi yu on dailymotion"
#cygstart /cygdrive/c/Program\ Files\ \(x86\)/Texmaker/texmaker.exe
#cygstart /cygdrive/d/dk_ze/Multiple_Mode_damage_imaging/Ultrasonics/Latex_related/SAGE\ LaTeX\ template
#cygstart /cygdrive/d/dk_ze/MUSIC_Laser_composites/C_17_aileron_paper/!PaperReviewReferences
#cygstart /cygdrive/d/dk_ze/D\ SHM
#cygstart "https://scholar-google-com.prox.lib.ncsu.edu/"
#cygstart /cygdrive/c/Program\ Files\ \(x86\)/Notepad++/Notepad++.exe
#cygstart /cygdrive/c/Program\ Files/Tracker\ Software/PDF\ Viewer/PDFXCview.exe
#cygstart /cygdrive/d/dk_ze/Multiple_Mode_damage_imaging/Ultrasonics/Latex_related/SAGE\ LaTeX\ template/mybibfile_v2.bib

cygstart "http://www.dailymotion.com/playlist/x52937" 


#cygstart "https://mail.google.com/mail/u/1/#inbox"
#cygstart "https://webmail.nianet.org/owa/#path=/mail"

