#!/bin/sh
echo "sk learn things"
cygstart /cygdrive/d/dk_ze/IamAProgrammer/Machine\ Learning/DataPythonUofM
cygstart jupyter notebook
cygstart chrome "https://www.coursera.org/learn/python-data-analysis/lecture/JvRF7/introduction"

cygstart chrome "https://www.coursera.org/learn/python-data-analysis/notebook/Um6Bz/assignment-2"
cygstart chrome "https://www.coursera.org/learn/python-data-analysis/notebook/KSSjT/assignment-3"
cygstart chrome "https://www.coursera.org/learn/python-data-analysis/notebook/TeDW0/assignment-4-project"


cygstart chrome "https://www.coursera.org/learn/python-data-analysis/notebook/3rRos/week-1-lectures-jupyter-notebook"
cygstart chrome "https://www.coursera.org/learn/python-data-analysis/notebook/G2dfj/week-2-lectures-jupyter-notebook"
cygstart chrome "https://www.coursera.org/learn/python-data-analysis/notebook/WxInF/week-3-lectures-jupyter-notebook"

cygstart chrome "https://github.com/sidsriv/Introduction-to-Data-Science-in-python/blob/master/Assignment%2B2.ipynb"

cygstart chrome "https://github.com/yanniey/Coursera_Intro_to_Data_Science_with_Python"





#cygstart /cygdrive/d/dk_ze/IamAProgrammer/Python/scikit-learnMLfromDataSchool.docx
#cygstart "https://www.youtube.com/watch?v=3ZWuPVWq7p4&index=5&list=PL5-da3qGB5ICeMbQuqbbCOQWcS6OYBr5A#t=551.634096/"
#cygstart /cygdrive/c/ProgramData/Anaconda3/Scripts/anaconda-navigator.exe
#jupyter notebook




#cygstart /cygdrive/d/dk_ze/Multiple_Mode_damage_imaging/Ultrasonics/Latex_related/SAGE\ LaTeX\ template
#cygstart /cygdrive/d/dk_ze/MUSIC_Laser_composites/C_17_aileron_paper/!PaperReviewReferences
#cygstart /cygdrive/d/dk_ze/D\ SHM
#cygstart "https://scholar-google-com.prox.lib.ncsu.edu/"
#cygstart /cygdrive/c/Program\ Files\ \(x86\)/Notepad++/Notepad++.exe
#cygstart /cygdrive/c/Program\ Files/Tracker\ Software/PDF\ Viewer/PDFXCview.exe
#cygstart /cygdrive/d/dk_ze/Multiple_Mode_damage_imaging/Ultrasonics/Latex_related/SAGE\ LaTeX\ template/mybibfile_v2.bib
