#!/bin/sh

echo "Open the folder for princeton university"
#cygstart /cygdrive/Users/Administrator1/Desktop/alljh/parents_to_us
cygstart /cygdrive/c/Users/Administrator1/Dropbox\ \(Princeton\)/Sync/princeton

#cygstart jupyter notebook
#cygstart chrome "http://sundog-education.com/datascience/"
#cygstart chrome "https://www.udemy.com/data-science-and-machine-learning-with-python-hands-on/learn/v4/content"
#cygstart /cygdrive/d/dk_ze/IamAProgrammer/Machine_Learning/DataSciencePython/DataScience/concepts.pptx


