#!/bin/sh

echo "Open the folder for NIA"
cygstart /cygdrive/c/JH_fast/LlrtmGuidedWaveTomoPaper/experiment/wave_alignment/20180425_100k/Radon20180426
#cygstart jupyter notebook
#cygstart chrome "http://sundog-education.com/datascience/"
#cygstart chrome "https://www.udemy.com/data-science-and-machine-learning-with-python-hands-on/learn/v4/content"
#cygstart /cygdrive/d/dk_ze/IamAProgrammer/Machine_Learning/DataSciencePython/DataScience/concepts.pptx


