#!/bin/sh

echo "copy all files in current folder to jiazeh@paris:/home/jiazeh/temp"

#firefox "https://www.google.com/"

#cd /home/jiazeh/Desktop/my_files/my_bin

scp -r ./* jiazeh@paris:/home/jiazeh/temp
