#!/bin/sh

echo "copy all files in current folder to jiazeh@tigercpu:/scratch/gpfs/jiazeh/temp"

#firefox "https://www.google.com/"

#cd /home/jiazeh/Desktop/my_files/my_bin

scp -r ./* jiazeh@tigercpu:/scratch/gpfs/jiazeh/temp
