#!/bin/sh
echo "open my python practices and notebooks"
#cygstart /cygdrive/c/Program\ Files\ \(x86\)/Texmaker/texmaker.exe
#cygstart /cygdrive/d/dk_ze/Multiple_Mode_damage_imaging/Ultrasonics/Latex_related/SAGE\ LaTeX\ template
#cygstart /cygdrive/d/dk_ze/MUSIC_Laser_composites/C_17_aileron_paper/!PaperReviewReferences
#cygstart /cygdrive/d/dk_ze/D\ SHM
#cygstart "https://scholar-google-com.prox.lib.ncsu.edu/"
#cygstart /cygdrive/c/Program\ Files\ \(x86\)/Notepad++/Notepad++.exe
#cygstart /cygdrive/c/Program\ Files/Tracker\ Software/PDF\ Viewer/PDFXCview.exe
#cygstart /cygdrive/d/dk_ze/Multiple_Mode_damage_imaging/Ultrasonics/Latex_related/SAGE\ LaTeX\ template/mybibfile_v2.bib


cygstart "http://localhost:8888/notebooks/w3resourceReal.ipynb"
cygstart /cygdrive/d/dk_ze/IamAProgrammer/Python/
cygstart /cygdrive/d/dk_ze/IamAProgrammer/Python/w3resource.docx 
cygstart "http://www.w3resource.com/python-exercises/python-basic-exercises.php"

