#!/bin/sh
echo "Tex setup for LSRTM"
cygstart /cygdrive/c/Program\ Files\ \(x86\)/Texmaker/texmaker.exe
cygstart /cygdrive/d/dk_ze/Wavefield_inversion_in_SHM/LlrtmShmPaper
cygstart /cygdrive/d/dk_ze/D\ SHM
cygstart /cygdrive/d/dk_ze/Wavefield_inversion_in_SHM/LSRTM_deve
cygstart chrome "https://scholar-google-com.prox.lib.ncsu.edu/"
cygstart firefox "http://www.thefreedictionary.com/serve"
cygstart /cygdrive/c/Program\ Files/Tracker\ Software/PDF\ Viewer/PDFXCview.exe
#cygstart /cygdrive/d/dk_ze/Multiple_Mode_damage_imaging/Ultrasonics/Latex_related/SAGE\ LaTeX\ template/mybibfile_v2.bib
cygstart /cygdrive/d/dk_ze/Wavefield_inversion_in_SHM/LlrtmShmPaper/Wavefield20170616.tex