#!/bin/bash 

## plot all vp/vs in the output folder 
## (obspy) jiazeh@farm:~/inversion_test$ vi zplotallmodel
## a subroutine to the zbash_try shorter 

## created on Sun Nov  4 10:13:31 EST 2018
## created by Jiaze He

## revisd on Sat Nov 24 14:47:16 UTC 2018
## get rid of '.' in front of /output

. ./zpara_headers

filename2=$1   # 'vp','vs','*'(for *, see what has been excluded for plotting in zplotbin)

echo 'dododo'
echo 'jobs_perchuck' $jobs_perchuck

xz_dirname=$(printf "model_init")
for i in `seq 0 $Nloop`;do
        for j in `seq 1 $jobs_perchuck` ;do
        k=$(($jobs_perchuck*$i+$j))
        if [ "$k" -le "$Nit" ]
        then

        echo 'k', $k
        echo 'Nit', $Nit
        #break  # Skip entire rest of loop.
        #fi
        K="$(printf "%04d" $k)"
        dirname=$(printf "output/model_$K")

        #dirname=$(printf "./output/model_$K")
        #fullp=$(printf "./output/model_$K_$filename2.bin");
        echo 'dirname', $dirname
        ./zPrintgllmap $xz_dirname $dirname $K $filename2 &
       # ./zplotbin $dirname $filename2 $k &
        fi
        done
wait
done
