#!/bin/sh
echo "open XMind"

cygstart /cygdrive/d/dk_ze/IamAProgrammer/How\ to\ find\ a\ job\ 2017/job\ hunting\ preparation/xmind-portable-3.3.1.201212250029/XMind_Windows/XMind.exe

cygstart /cygdrive/d/dk_ze/IamAProgrammer/How\ to\ find\ a\ job\ 2017/job\ hunting\ preparation/xmind-portable-3.3.1.201212250029/XMind_Windows

#cygstart /cygdrive/d/dk_ze/IamAProgrammer/Machine_Learning/DataSciencePython/DataScience/DataScience-Python3

#cygstart /cygdrive/d/dk_ze/IamAProgrammer/Machine_Learning/DataSciencePython/DataScience

#cygstart /cygdrive/d/dk_ze/IamAProgrammer/Machine_Learning/Hands_On_Machine_Learning_with_Scikit_Learn_and_TensorFlow

#cygstart /cygdrive/d/dk_ze/IamAProgrammer/Machine_Learning/Hands_On_Machine_Learning_with_Scikit_Learn_and_TensorFlow/Hands_On_Machine_Learning_with_Scikit_Learn_and_TensorFlow.pdf

