#!/bin/sh

echo "Open the folder for TeamViewer"
#cygstart /cygdrive/c/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Notepad\+\+/Notepad\+\+
/cygdrive/c/Program\ Files\ \(x86\)/TeamViewer/TeamViewer  
#cygstart jupyter notebook
#cygstart chrome "http://sundog-education.com/datascience/"
#cygstart chrome "https://www.udemy.com/data-science-and-machine-learning-with-python-hands-on/learn/v4/content"
#cygstart /cygdrive/d/dk_ze/IamAProgrammer/Machine_Learning/DataSciencePython/DataScience/concepts.pptx


