#!/bin/sh

echo "Open the signal 225 from source 1, receiver spacing 1"
#cygstart /cygdrive/Users/Administrator1/Desktop/alljh/parents_to_us
cygstart /cygdrive/c/Users/Administrator1/Dropbox\ \(Princeton\)/Sync/princeton/Medical_FWI_research_mine/transducer_modeling/implementation_specfem/more_detailed_comparison_20180919/more_baseline/1act_1sensor181_241_norotate/filtering_src01rec225.tif

#cygstart jupyter notebook
#cygstart chrome "http://sundog-education.com/datascience/"
#cygstart chrome "https://www.udemy.com/data-science-and-machine-learning-with-python-hands-on/learn/v4/content"
#cygstart /cygdrive/d/dk_ze/IamAProgrammer/Machine_Learning/DataSciencePython/DataScience/concepts.pptx


