#!/bin/bash

# created around 20180625
# revised 
# Wed Jul  4 16:50:35 EDT 2018


. zpara_headers


#f0=$(sed -n 1,15p specfem_data/SOURCE_000000 | grep 'f0' | cut -d\= -f2 | tr -d '[:space:]')
#
#intf0=${f0%.*}
#echo 'intf0 ='$intf0
#
##nx=$(sed -n 266,268p DATA/Par_fie | grep 'nx' | cut -d\= -f2 | tr -d '[:space:]')
#nx=`grep ^nx specfem_data/Par_file | cut -d = -f 2 | cut -d \# -f 1 | tr -d ' '`
#echo 'nx ='$nx
#
#D_T=`grep ^DT specfem_data/Par_file | cut -d = -f 2 | cut -d \# -f 1 | tr -d ' '| sed 's/-/\_/g'`
#echo 'D_T ='$D_T
#
#NSTEP=$(sed -n 26,28p specfem_data/Par_file | grep 'NSTEP' | cut -d\= -f2 | tr -d '[:space:]')
#echo 'NSTEP ='$NSTEP

foldname_for_results_saving=$(printf "$HOME/data_bk/inversion_test_data/noutput_intf0_${intf0}_nx${nx}_D_T${D_T}_NSTEP${NSTEP}")
echo 'bk path is '$foldname_for_results_saving

        if [ -d "$foldname_for_results_saving" ]; then
        echo 'delete and make the folder'
        rm -r "$foldname_for_results_saving"
	mkdir "$foldname_for_results_saving"
        else
        echo 'make a folder'
        mkdir "$foldname_for_results_saving"
        fi

        wait

cp -r ./* "$foldname_for_results_saving"/ 
        wait

path_remote=$(printf "jiazeh@paris:/home/jiazeh/data_bk/inversion_test_tiger_data")
echo 'remote path is '$path_remote

       # if [ -d "$foldname_for_results_saving_remote" ]; then
       # echo 'nothing'
       # else
       # echo 'make a folder'
       # mkdir "$foldname_for_results_saving_remote"
       # fi
#
scp -qr ${foldname_for_results_saving} ${path_remote}

       wait
echo "copying files has been completed"












