#!/bin/bash


import sys 
import numpy as np

from glob import glob
from os.path import join

from seisflows.tools import msg 
from seisflows.tools import unix
from seisflows.tools.tools import divides, exists
from seisflows.config import ParameterError, save
from seisflows.workflow.base import base

PAR = sys.modules['seisflows_parameters']
PATH = sys.modules['seisflows_paths']

print 'hey'






