#!/bin/bash

for i in `seq 1 3`;
do
	echo "item: $i"
	sed -i "s:seismotype.*:seismotype                      = $i              # record 1=displ 2=veloc 3=accel 4=pressure 5=curl of displ 6=the fluid potential:g" Patry
	grep -n "seismotype" Patry
done
