#!/usr/bin/env python

# recover several seismo signals 
# created on Fri Jul 27 16:37:35 UTC 2018
# by Jiaze He 

#%matplotlib notebook
import matplotlib.pyplot as plt
import pandas as pd
import pickle
#import cPickle as pickle

with open('OUTPUT_FILES/U_norm.pickle', 'rb') as pickle_file:
    figx = pickle.load(pickle_file)
    plt.show()




